"""Track-distinctive identifiers a mandate must not contain.

A mandate says how a seat works. Naming this problem's answer in it is overfitting, so
`harness check` scans every file in `mandates/` against the list below and reports the
file and the line. Track-specific detail belongs in the task you give the band in the
room, not in a mandate.

**Generated from the specs** by `python -m harness.mandate_audit --emit-vocabulary`, and
identical to the list the organizers audit against after submissions close. Ordinary
words the specs happen to use -- `amount`, `balance`, `handle`, `status`, `available` --
are not here, because banning them would fail everyone. Error codes and fixture
identifiers are, because they are this problem's answer.
"""
import re

# Identifier shapes only. Prose, numbers and quoted fragments are not evidence of
# anything, and a term that needs a judgement call does not belong in a scan whose
# output is a disqualification. A path starts a token: in `import/export` the slash
# joins two words.
SHAPES = (
    ("endpoint", re.compile(r"(?<![a-z0-9_])/[a-z][a-z0-9_]*(?:[/-][a-z0-9_{}]+)*")),
    ("identifier", re.compile(r"\b[a-z][a-z0-9]*(?:_[a-z0-9]+)+\b")),
    ("test id", re.compile(r"\b[a-z][a-z0-9]*(?:-[a-z0-9]+)+\b")),
)


def terms_in(text: str):
    """(kind, term) for every identifier-shaped token in `text`, lowercased."""
    lowered = text.lower()
    for kind, pattern in SHAPES:
        for term in pattern.findall(lowered):
            yield kind, term


TRACK_VOCABULARY = {
    'toy': (
    ),
    'tablekeeper': (
        '/auth/login',
        '/auth/signup',
        '/availability',
        '/lookup',
        '/reservation-moves',
        '/reservations',
        '/reservations/{reference}',
        '/reservations/{reference}/cancel',
        '/reservations/{reference}/decision',
        '/reservations/{reference}/history',
        '/restaurants',
        '/restaurants/{id}',
        '/restaurants/{id}/policies',
        '/restaurants/{id}/replans',
        '/restaurants/{id}/replans/{plan_id}/apply',
        '/series',
        '/series/{series_id}',
        '/series/{series_id}/amend',
        'accepted_terms',
        'already_in_series',
        'anchor_reference',
        'auth-error',
        'availability-grid',
        'available_options',
        'available_table_ids',
        'booking-error',
        'booking-form',
        'booking-party-size',
        'booking-submit',
        'booking-summary',
        'booking-uncertain',
        'cancellation_cutoff_minutes',
        'combination_not_allowed',
        'confirmation-details',
        'confirmation-reference',
        'confirmation-tables',
        'current-user',
        'cutoff_passed',
        'data-available',
        'date-input',
        'effective_from',
        'email_taken',
        'ends_at',
        'expected_revision',
        'format_version',
        'from_index',
        'idempotency_key_reuse',
        'interval_weeks',
        'invalid_local_time',
        'local_time',
        'login-email',
        'login-password',
        'login-submit',
        'logout-button',
        'lookup-reference-input',
        'lookup-submit',
        'malformed_request',
        'manager_user_ids',
        'missing_idempotency_key',
        'moved_count',
        'new_york',
        'no-slots',
        'no_feasible_plan',
        'no_overlap',
        'not_found',
        'not_on_slot_grid',
        'opening_hours',
        'outside_opening_hours',
        'party-size-input',
        'party_exceeds_capacity',
        'party_size',
        'plan_already_applied',
        'plan_id',
        'planning_limit',
        'policy_version',
        'r_anker',
        'res_7',
        'reservation-cancel-button',
        'reservation-detail',
        'reservation-error',
        'reservation-moves',
        'reservation-status',
        'reservation-tables',
        'reservation_cancelled',
        'reservation_duration',
        'reservation_duration_minutes',
        'reservation_id',
        'restaurant-select',
        'restaurant_id',
        'restaurant_revision',
        'search-button',
        'series_id',
        'signup-display-name',
        'signup-email',
        'signup-password',
        'signup-submit',
        'slot_minutes',
        'stale_plan',
        'stale_revision',
        'starts_at',
        'starts_at_local',
        'table_id',
        'table_ids',
        'table_unavailable',
        'u_ada',
        'unused_seats',
        'validation_failed',
    ),
    'pocketful': (
        '/activity',
        '/auth/login',
        '/auth/signup',
        '/authorizations',
        '/authorizations/{id}/capture',
        '/authorizations/{id}/void',
        '/correction-batches',
        '/payments',
        '/payments/{payment_id}/corrections',
        '/payments/{payment_id}/refunds',
        '/payments/{payment_id}/revisions',
        '/requests',
        '/requests/rq_4/pay',
        '/requests/{id}/cancel',
        '/requests/{id}/decline',
        '/requests/{id}/pay',
        '/settlements',
        '/split',
        '/splits',
        '/statement',
        'activity-amount',
        'activity-item',
        'activity-list',
        'activity-note',
        'activity-parties',
        'as_of',
        'auth-error',
        'authorization-amount',
        'authorization-capture',
        'authorization-capture-amount',
        'authorization-captured',
        'authorization-error',
        'authorization-expires',
        'authorization-item',
        'authorization-list',
        'authorization-void',
        'authorization_expired',
        'authorization_id',
        'authorization_not_open',
        'authorization_ttl_seconds',
        'authorize-amount',
        'authorize-error',
        'authorize-handle',
        'authorize-note',
        'authorize-submit',
        'authorize-visibility',
        'balance_after',
        'capture_exceeds_authorization',
        'captured_amount',
        'closed_at',
        'closing_balance',
        'committed_at',
        'correction-batches',
        'correction_batch_id',
        'current-handle',
        'current-user',
        'data-amount',
        'data-status',
        'data-visibility',
        'effective_at',
        'email_taken',
        'empty-activity',
        'empty-authorizations',
        'empty-requests',
        'expected_revision',
        'expires_at',
        'format_version',
        'from_handle',
        'from_user_id',
        'handle_taken',
        'historical_overdraft',
        'idempotency_key_reuse',
        'incoming-list',
        'incomplete_settlement',
        'insufficient_funds',
        'invalid_refund_target',
        'known_at',
        'linked_payment_immutable',
        'login-email',
        'login-password',
        'login-submit',
        'logout-button',
        'malformed_request',
        'minor_units',
        'missing_idempotency_key',
        'not_found',
        'opening_balance',
        'outgoing-list',
        'participant_handles',
        'pay-amount',
        'pay-error',
        'pay-handle',
        'pay-note',
        'pay-submit',
        'pay-uncertain',
        'pay-visibility',
        'payer_handle',
        'payer_id',
        'payment_id',
        'payment_ids',
        'recorded_at',
        'refund_exceeds_payment',
        'refund_of',
        'remaining_amount',
        'request-amount',
        'request-cancel',
        'request-decline',
        'request-error',
        'request-handle',
        'request-item',
        'request-note',
        'request-pay',
        'request-submit',
        'request_id',
        'request_not_pending',
        'requester_handle',
        'requester_id',
        'rq_1',
        'rq_4',
        'self_payment',
        'self_request',
        'settlement_id',
        'settlement_operator_ids',
        'signup-display-name',
        'signup-email',
        'signup-password',
        'signup-submit',
        'sp_2',
        'split-amount',
        'split-error',
        'split-handles',
        'split-note',
        'split-preview',
        'split-share',
        'split-submit',
        'split_id',
        'stale_revision',
        'to_handle',
        'to_user_id',
        'u_ada',
        'u_bob',
        'validation_failed',
        'wallet-available',
        'wallet-balance',
        'wallet-held',
        'wallet-refresh',
    ),
}


def for_track(track: str) -> tuple[str, ...]:
    return TRACK_VOCABULARY.get(track, ())
